# Generated by Django 3.2 on 2023-05-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230529_2109'),
    ]

    operations = [
    ]
